sudo: required

language: python

services:
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

script:
  - docker image build -t xcbuild:latest .
  - docker tag xcbuild:latest mattpaletta/xcbuild:latest

after_success:
  - docker push mattpaletta/xcbuild:latest
