sudo: required
services:
  - docker

before_install:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=mattpaletta/xcbuild
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

script:
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tagmy_example_app:latest
  
after_success:
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
